openzim/sotoki

requirements.txt, sotoki/sotoki.py
=> Better file type checking

sotoki/sotoki.py
=> Remove resize_image_profile()

sotoki/sotoki.py
Fixes #111 
Fixes #96 
The gif2apng error is fixed in this and some exception handling code is implemented. @kelson42 @rgaudin please have a look.
=> Fix gif2apng fail and add exception handling

sotoki/sotoki.py
=> Change zimwriterfs FT option

sotoki/sotoki.py
This fixes #127 by adding proper calls to download and store images in comments.
=> Fixes #127 - Add support for image in comments

sotoki/sotoki.py
=> Fixes #122 - Don't create temporary files if error while downloading

requirements.txt, sotoki/sotoki.py
Fixes #131 by properly detecting and converting Windows icon to PNG format
=> Fixes #131 - Properly detect icon and convert to PNG

sotoki/sotoki.py
Fixes #129 by changing the redirection format to accommodate human errors in internal links
=> Fixes #129 - Change redirection format

sotoki/sotoki.py
Fixes #137 by not returning empty string from markdown()
=> Fixes #137 - Don't crash on empty text in comment

Dockerfile, requirements.txt, sotoki/sotoki.py
Fixes #104 . This introduces optimization cache using kiwixstorage. I've tested this and it works. Will update the requirements file in the next commit. I would also like to point out a few things. 
1. We should go with self-destructing an object after a certain period of time. I currently don't have an idea of the specific duration we should use. I think going through recipes in Zimfarm would help. (Maybe we can create another argument for that)
2. The method has_object_matching_meta() in kiwixstorage only checks for one value. I think we should extend it to check multiple tags in the meta. (Please correct me if I'm wrong)
Also, I've made some inline comments. @rgaudin @dattaz @kelson42 can you please suggest changes/improvements.
=> Fixes #104 - Enable optimization cache

CHANGELOG.md, sotoki/sotoki.py
Fixes #142 by raising an exception from download_image()
=> Fixes #142 - Raise exception if download_image fails to download

sotoki/sotoki.py
This fixes images not being resized as PIL returns new object with Image.resize()
=> Fix image resizing

sotoki/sotoki.py
Adds new formatting from black 20.8
=> Add new black formatting

CHANGELOG.md, sotoki/sotoki.py, sotoki/templates/alltags.html, sotoki/templates/index.html, sotoki/templates/post.mixin.html, sotoki/templates/question.html, sotoki/templates/tag.html, sotoki/templates/tags.html
Fixes #168 by removing `.html` extensions from all articles
=> Remove .html extension from articles

CHANGELOG.md, sotoki/sotoki.py
=> return 1 on zim making failure

CHANGELOG.md, sotoki/sotoki.py
This fixes #177 by handling absolute root link `/`
=> Handle root link

sotoki/sotoki.py
=> Add option to remove all external link

sotoki/sotoki.py
=> Option : dont include unanswered questions

sotoki/sotoki.py
Updated to https in place of http
This fixes #175
=> updated https in place of http

src/sotoki/archives.py, src/sotoki/constants.py, src/sotoki/entrypoint.py, src/sotoki/posts.py, src/sotoki/scraper.py, src/sotoki/tags.py, src/sotoki/users.py, src/sotoki/utils/database.py, src/sotoki/utils/generator.py, src/sotoki/utils/preparation.py, src/sotoki/utils/s3.py, src/sotoki/utils/sites.py, src/sotoki/utils/system.py
This adds basic support for consuming XML content and adding to ZIM.
All files are read and walked-through and this creates a ZIM with straight XML content so no formatting, no processing, no external data such as images, etc.
Temp data (that needs reuse) is stored in SQLite or redis. We'll need to complete processing/formatting to be better informed about which is faster/more efficient.
=> WIP XML parsing

src/sotoki/posts.py, src/sotoki/tags.py, src/sotoki/users.py, src/sotoki/utils/database.py, src/sotoki/utils/html.py
Hopefully removes the memory-leak.
My test so far on a smaller dataset:
=> Better database commit strategy

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/docker.yml, src/sotoki/utils/preparation.py
Fix #298 
Changes:
- upgrade Github actions
- import `xml.sax.saxutils` instead of `xml.sax`
=> Fix saxutils

README.md
This about making more visible the supported versions of Python
=> Add Python version badges

CHANGELOG.md, src/sotoki/archives.py, src/sotoki/constants.py, src/sotoki/dependencies.py, src/sotoki/utils/preparation.py
Fix #301 
Fix #313 
- upgrade to jdenticon 3.3.0 to properly load user icons
- revert all modifications linked to adaptations to unwanted SE dump changes
=> Revert XML adaptations and upgrade jdenticon
