- sotoki/sotoki.py
According to [this answer](https://meta.stackexchange.com/a/164197) the part after / in a link is an user id and useless in our case.
As explain in #68 59 is not the right answer_post_id but it is the user_id of user who post the question.
fix #68
> Answers_post_id is the first number after a/

- sotoki/sotoki.py
The decompression of dump files can take an extremely long time. Hence, it is appropriate to send a warning before the process begins.
This PR provides a solution to [Issue 91](https://github.com/openzim/sotoki/issues/91).
> Added a warning before start of dump decompress

- sotoki/sotoki.py
Tested on conlang which was not in list without issue.
Will need a full pass on all domains to ensure it's safe
> Fixed #98: enabled mathjax everywhere

- sotoki/sotoki.py
Following discussion on openzim/libzim/issues/298, add namespace of the target_url in the redirect TSV file.
> Fixed #95: specify namespace in target_url part of redirect TSV

- CHANGELOG.md
- requirements.txt
- sotoki/sotoki.py
- inside build directory (as /magick)
- removed once complete
Also replaced `subprocess32` (dep) with `subprocess` (stdlib) as not required anymore.
Adding a print on image optimization timeout
Increasing image optim timeouts
> Fixed #85: using different temp path for imagemagick

- CHANGELOG.md
- Dockerfile
- sotoki/sotoki.py
This is an alternative solution to #84 that should be safer and more efficient than #101 
- combined download and optimization of image in a single function
- downloads to `/dev/shm` if avail (linux)
- optimize in place (or in the same dir -- gif resize)
- move file from there to requested path
- use same function for both profile pics and images
> Image optim and resize in memory (/dev/shm) if possible

- sotoki/sotoki.py
in case image optimization raises an exception, the source file was not moved
to destination, resulting in missing image or user profile gen.
> make sure failed-to-optimize image are not left behind

- requirements.txt
- sotoki/sotoki.py
This fixes #108 and some small typos in sotoki.py
Previously the following thew error in processing questions (At around 96000 questions)
`sotoki wordpress.stackexchange.com Kiwix --threads=1 --reset --clean-previous --no-userprofile --nopic --nozim`
However, this works as expected now.
> Fixes #108 - Bump mistune version to 2.0.0a3

- requirements.txt
- sotoki/sotoki.py
This bumps beautifulsoup4 and Pillow to their latest versions. I have verified that the scraper works and everything seems to work properly. However, @rgaudin, @dattaz please check this once.
> Bump dependencies to latest versions

- sotoki/sotoki.py
Fixes #133 by sending non HTML escaped string to `mistune` and using `plugin_url`
> Fixes #133 - Send non HTML escaped string to mistune and use plugin_url

- CHANGELOG.md
- sotoki/sotoki.py
This does the following -
- log on successful downloads
- do not depend on headers for filetype identification
- use Pillow to convert images (except GIF) to PNG
- use Pillow to resize images (except GIF)
Fixes #147 and #146 by not depending on ImageMagick (except for GIFs) and not using content-type header for filetype identification.
Also, adds logs on successful downloads/uploads because it seems that it may play in important role in further debugging.
> Less dependence on ImageMagick and better filetype identification

- requirements.txt
- sotoki/sotoki.py
This fixes 403 errors (as mentioned [here](https://github.com/openzim/sotoki/issues/145#issuecomment-643592059)) by using save_large_file from zimscraperlib
> Download using save_large_file from zimscraperlib

- sotoki/sotoki.py
This adds --no-tmpfs-dir to set TMPFS_DIR to None even if we have /dev/shm available. This will help narrow down #145 
This is a temporary addition and shall be removed after #145 is fixed (adding a label for that)
> Add --no-tmpfs-dir

- sotoki/sotoki.py
Fixes #154 by using shutil.move instead of os.rename
> Use shutil.move instead of os.rename in nopic mode

- sotoki/sotoki.py
This shall fix #145 and rollback changes made in #155 and 96fbb557cf06bc03dff6970a579f2d27f601a6de 
The processes got stuck as some servers didn't close the connection (either with or without error). One suck example is an image that was being downloaded from the discord server.
This PR does the following -
- Add timeout to HEAD request in get_meta_from_url() (Timeout is 20s and 5 retries are allowed)
- Increase timeout for advdef to 60s and enable it
- Roll back changes in #155
> Add timeout to HEAD request and rollback temporary changes

- sotoki/sotoki.py
This fixes #152 by properly handling files if extension is different from the filetype detected.
This includes the following changes -
- download_image() - 
1. check_and_optimize is called instead of directly calling optimize_one()
check_and_optimize is a new function which checks the extension and the detected filetype and creates temp files if necessary
2. If detected filetype is not one which we can handle, we now raise an Exception
- image() - We now modify the image links only if download_image() succeeded
- create_temporary_copy() - Updated to create the temporary copy with a given suffix
- check_and_optimize() - This is a new function to handle extension and filetype checking, making temp file if necessary, calling optimize_one(), and copying optimized image from temporary copy to …
> Create temp files if extension is wrong while optimizing

- CHANGELOG.md
- sotoki/sotoki.py
This fixes #164 by adding a `--no-identicons` option to create smaller ZIMs by skipping download of identicons and using only the autogenerated ones.
> Add --no-identicons option

- CHANGELOG.md
- sotoki/sotoki.py
Addresses #161. This does the following -
- Fix tag links
- The user profile links now redirect to online instances if `--nouserprofile` option is passed
- The variable `static_folder` is replaced with `output_dir` as it was changed before.
This still cannot two links, one of them being a user comment with a answer ID that doesn't exist and the other one being a tag abc* type link which is resolved into abc-a, abcb, abcx .. etc. For this we need to write a redirect or somehow need to store such links till the process of writing tag HTMLs.
> Fix some dead links

- src/sotoki/dependencies.py
- src/sotoki/templates/base.html
- src/sotoki/templates/user.html
- src/sotoki/templates/user_card.html
- src/sotoki/templates/users.html
- src/sotoki/users.py
- src/sotoki/utils/html.py
- src/sotoki/utils/imager.py
Added WebP Hero polyfill on images:
- images now named ending with `.webp` in ZIM
- polyfill scripts included always (350KB) in page
- polyfill applied on loading error with a fallback to jdenticon
- regular loading + jdenticon fallback for browsers with WebP support
- using <img /> elements instead of <object />
- jdenticon dynamically replacing failing <img /> (requires JS)
> Added WebP Polyfill

- .github/workflows/ci.yml
- Builds the docker image
- Runs the scraper using docker image
- Launched zimcheck --empty --checksum --integrity --metadata --favicon --main --mime --details on resulting zim
Currently fails due to https://github.com/openzim/zim-tools/issues/249
> Added CI build for test scraper

- src/sotoki/archives.py
- src/sotoki/constants.py
- src/sotoki/entrypoint.py
- src/sotoki/posts.py
- src/sotoki/scraper.py
- src/sotoki/tags.py
- src/sotoki/users.py
- src/sotoki/utils/__init__.py
- src/sotoki/utils/database.py
- src/sotoki/utils/imager.py
- src/sotoki/utils/progress.py
First version of Progress reporter:
- Displays progress on log (INFO level)
- Dumps computed progress to JSON file if using --stats-filename (zimfarm)
Progress is printing on every 10K updates or every 5mn if there hasn't been that
many updates since.
Progress is split accross 7 steps each being assigned an arbitrary weight:
PREPARATION_STEP: 5
TAGS_METADATA_STEP: 2
QUESTIONS_METADATA_STEP: 10
USERS_STEP: 5
QUESTIONS_STEP: 30
TAGS_STEP: 2
LISTS_STEP: 1
In addition, we account Image “processing” a weight of 60. This processing can be
either downloading source, convertion, optimization, upload, add to zim or just
download-from-s3, add to zim.
Those weights are __arbitrary__ and will be updated once we have enough data to pick
better values
Every question/user/tag processed (parsed, stored, …
> Implemented progress reporting

- src/sotoki/assets/static/css/sotoki.css
- src/sotoki/renderer.py
- src/sotoki/scraper.py
- src/sotoki/templates/base.html
- src/sotoki/templates/questions.html
- src/sotoki/templates/user.html
Following SE, we previously had two versions of the user profile, triggered by
some _mobile_ device detection in JS.
This was bad for several reasons:
- No JS had broken User profiles
- dependency on MathJax JS for that detection
- User profile content inserted twice (storage, DB queries)
- Complexity of templates and code (mobile.css conflicts with primary.css)
We now have a custom, SE inspired User profile that is responsive down to mobile as well
Additionaly:
- we don't download mobile.css from source
- we moved our growing css to a dedicated file (sotoki.css)
- topbar and rest of mobile-specific is now triggered solely by media queries
- part of sotoki.css is copied from mobile.css
- fixed link to home on questions list
- fixed links to webppolyfill on non-root paths
- fixed jdenticon …
> User profile now responsive

- src/sotoki/utils/imager.py
This changes the way image files are named from the more collision-prone Adler32 checksums to MD5 hashes
Fixes #284
> Use MD5 when naming image files

- CHANGELOG.md
- src/sotoki/entrypoint.py
- src/sotoki/scraper.py
Resolves #291
Updated publisher metadata to 'openZIM' in `entrypoint.py` and `scraper.py`.
> Update publisher metadata from 'Kiwix' to 'openZIM'

- Dockerfile
Fix #294 
Align Debian release (`buster` for now) between the Redis image and the final container image
Nota: we will obviously have to upgrade to bookworm and Python 3.12 at some point, but let's live with it for the coming weeks
> Use same Debian release for redis and final container

- requirements.txt
- src/sotoki/constants.py
- src/sotoki/entrypoint.py
- src/sotoki/scraper.py
- src/sotoki/utils/shared.py
(PR depends on https://github.com/openzim/python-scraperlib/pull/126 and will likely need at least one revision due to some feedback being needed)
This PR upgrades `python-scraperlib` to 3.x while also adding a `--long-description argument`. This implements #290.
**Changes:**
- upgrade python-scraperlib
- add `--long-description` argument (`--description` already exists and was not needed to be added). It defaults to the tagline.
- The `Description` metadata is now limited in length to conform with python-scraberlibs metadata validation, which enforces a maximum length
- `Flavour` and `Scraper` metadata will now be set
**Test status:**
- tested manual build with `sotoki --debug --domain="boardgames.stackexchange.com" --mirror="https://org-kiwix-stackexchange.s3.us-west-1.wasabisys.com" …
> Upgrade python-scraperlib to 3.X (implement #290)

- CHANGELOG.md
- Dockerfile
- src/sotoki/entrypoint.py
This PR updates the default behavior of the --redis-url argument to read from the REDIS_URL environment variable, falling back to redis://localhost:6379 when not set.
Inside Docker, this allows the scraper to use the Unix socket without passing the argument explicitly.
Closes: #333
> Fix #333: Update --redis-url to use REDIS_URL env var by default

- CHANGELOG.md
- requirements.txt
- src/sotoki/utils/imager.py
- src/sotoki/utils/misc.py
- src/sotoki/utils/shared.py
This is an interim solution for #326
It is only interim because it does not really take into account 429 errors, since it only randomly retries a bit later. And since we have multiple calls in parallel, it could be that we still make too many request, or that the retry arrives at a moment where we are already making too many requests. The probability is reduced by the fact that we use only 10 threads instead of 100 (looks like it is an acceptable compromise, we will see if it causes scrape to take too long)
It is not the proper solution on the long term where we should automatically reduce the number of requests in parallel, and add a pause if needed, but only for requests of a given domain. This was deemed way too difficult to implement given current code structure: we do not expect to …
> Reduce number of workers and add backoff on 429 and non-HTTP (network, ...) errors
